### ISSUE TITLE
Problems with Google Authenticator, Magento 1.7, PHP 7

### ISSUE THREAD

**Issue by aricwatson** [nexcess/magento-sentry-two-factor-authentication#1]
Reported bug, under Magento 1.7 running PHP7. 

When linking google authenticator with a device, the QR code is displayed and scans correctly. The 'continue' button does not work, and user cannot login to the admin account any more.

Using Duo works fine.

**Comment by EricSeastrand** [comment]
Possibly related to #14 #10
Do you get any errors in your developer tools console?

**Comment by rfxn** [comment]
This issue looks to have been fixed by https://github.com/nexcess/magento-sentry-two-factor-authentication/commit/652147b2340d62a40b76bfe7c47ec337eff861a7

If this is still an issue, please feel free to reopen the issue.

Thanks
