### ISSUE TITLE
How can find my Qr code? i erase my phone and now cannot log withhout code

### ISSUE THREAD

**Issue by CiprianPoiana** [nexcess/magento-sentry-two-factor-authentication#18]
recently i erase my phone and now i cannot log in my admin panel because i don't have the key anymore.

**Comment by miguelbalparda** [comment]
When you set up the provider you should have gotten a QR code for cases like this. If you don't have it anymore then you will have to disable the module and recreate the 2 fact auth.

**Comment by CiprianPoiana** [comment]
Ok, i know that but i have anther problem...

i'm the onluy admin and cannot log in my account to create a new user.

[image: Magazinu' lu' peste®] <http://www.magazinulupeste.ro/>

Ciprian Poiana - Asistent Manager
Ovidiu Marcu - Manager

Iasi, Romania
Str. Hatman Sendrea Nr.21-23
+4 0785.737.227 (+4 0785.PESCAR)
+4 0332.440.592
www.magazinulupeste.ro
magazinulupeste@gmail.com
Localizare Google Maps
<https://www.google.com/maps/place/Magazinu'+lu'+peste+1/@47.1527885,27.5735954,15z/data=!4m2!3m1!1s0x0:0xf0667b2c4a018655?hl=en-US>


2016-12-10 13:35 GMT+02:00 Miguel Balparda <notifications@github.com>:

**Comment by miguelbalparda** [comment]
You will have to disable the module manually and/or create another user directly in the database in that case.

**Comment by CiprianPoiana** [comment]
Look whai i dooȘ
1. i delete the folder from server
2. i uninstall the module via Magento Connect
3. i search for eventualy file remaining after uninstall and delete them
4. i loged succesfully in may admin panel an i create a new user with admin
credentials
5. i reinstal the module via Magento Connect.

The problem persist when i try to disable module or to make any settings it
request to log in with two step verification this with both users.
I can't find the qr code for configuration. Not displayed anywhere.

 :(

[image: Magazinu' lu' peste®] <http://www.magazinulupeste.ro/>

Ciprian Poiana - Asistent Manager
Ovidiu Marcu - Manager

Iasi, Romania
Str. Hatman Sendrea Nr.21-23
+4 0785.737.227 (+4 0785.PESCAR)
+4 0332.440.592
www.magazinulupeste.ro
magazinulupeste@gmail.com
Localizare Google Maps
<https://www.google.com/maps/place/Magazinu'+lu'+peste+1/@47.1527885,27.5735954,15z/data=!4m2!3m1!1s0x0:0xf0667b2c4a018655?hl=en-US>


2016-12-10 14:01 GMT+02:00 Miguel Balparda <notifications@github.com>:

**Comment by miguelbalparda** [comment]
Have you removed the entries from the database?

**Comment by CiprianPoiana** [comment]
I don't do that, because i'm not sure how to do it, and i don't want to
broke something.

[image: Magazinu' lu' peste®] <http://www.magazinulupeste.ro/>

Ciprian Poiana - Asistent Manager
Ovidiu Marcu - Manager

Iasi, Romania
Str. Hatman Sendrea Nr.21-23
+4 0785.737.227 (+4 0785.PESCAR)
+4 0332.440.592
www.magazinulupeste.ro
magazinulupeste@gmail.com
Localizare Google Maps
<https://www.google.com/maps/place/Magazinu'+lu'+peste+1/@47.1527885,27.5735954,15z/data=!4m2!3m1!1s0x0:0xf0667b2c4a018655?hl=en-US>


2016-12-10 14:42 GMT+02:00 Miguel Balparda <notifications@github.com>:

**Comment by miguelbalparda** [comment]
You should be able to remove everything that matches "%turpentine%" inside the table core_config_data without causing any problems.

**Comment by miguelbalparda** [comment]
Closing for lack of feedback
