### ISSUE TITLE
Bug with PHP 5.3

### ISSUE THREAD

**Issue by matiasserrano** [nexcess/magento-sentry-two-factor-authentication#21]
Using PHP 5.3 this function from the helper breaks login.

`private function getIPWhitelist()
    {
        $return = [];
        ...
    }`

This should be changed to

`private function getIPWhitelist()
    {
        $return = array();
        ...
    }`

**Comment by miguelbalparda** [comment]
PHP 5.3 EOL was 2 years and 4 months ago, I strongly suggest you to use an updated version of PHP to avoid issues with this and any other module.
