### ISSUE TITLE
File for "Direct Download" not found

### ISSUE THREAD

**Issue by wilsonrf** [nexcess/magento-sentry-two-factor-authentication#27]
At the "Wiki > Installation & Configuration", at the "Installation" section, you say: "You can download the extension from this website. Once downloaded, install it on your Magento site with the Direct File Upload option in your system's Magento Connect Manager.", but I can't found the file anywhere on Github.
Please make it available at "releases".
Thanks in advance.
Best Regards.

**Comment by miguelbalparda** [comment]
Just tagged 1.0.5. Sorry about the delay.
