### ISSUE TITLE
Login issues with users that have limited permissions

### ISSUE THREAD

**Issue by aricwatson** [nexcess/magento-sentry-two-factor-authentication#6]
User is reporting getting access denied upon login, for users with limited permissions.

> I am on magento 1.9.4 
> The first time user enters username/pass and is taken to admin but gets a access denied message and also does not get to setup 2 factor. This is for a non admin user with limited permissions. Access areas are catalog, sales, customers, cms but only limited access to admin. cache, index and two factor authentication

**Comment by guroja** [comment]
Same issue here. The Managers account, who have access to backend with limited permission, like, products, sales, cache, index, etc. are getting permission denied. Please help

**Comment by jimbo11883** [comment]
I am also having this issue with a client.

**Comment by miguelbalparda** [comment]
@jimbo11883 can you add some more info about your issue? Log entries, screenshots and any other information you consider useful.

**Comment by jimbo11883** [comment]
After logging into Magento admin, I get the following page:
![screenshot-honigs com-2016-11-16-11-16-36](https://cloud.githubusercontent.com/assets/705845/20355173/70181f76-abee-11e6-9c6c-c80f510b10cb.png)

**Comment by jimbo11883** [comment]
It never gets to the TFA login screen. It doesn't log anything to two_factor_auth.log.

**Comment by miguelbalparda** [comment]
@jimbo11883 can you access Sales, Catalog, Customers, CMS or System when you see that screen?

**Comment by jimbo11883** [comment]
No, it gives you the same screen.

**Comment by miguelbalparda** [comment]
Can you show me how the admin user is configured?

**Comment by jimbo11883** [comment]
Sure.

![screenshot-honigs com-2016-11-16-12-17-15](https://cloud.githubusercontent.com/assets/705845/20357727/08a3d6f6-abf7-11e6-9578-92ec90e6bef3.png)
![screenshot-honigs com-2016-11-16-12-19-50](https://cloud.githubusercontent.com/assets/705845/20357728/08a9406e-abf7-11e6-80de-e3db5b62a5b6.png)

**Comment by miguelbalparda** [comment]
Can you try adding the Dashboard permission for this user role?

**Comment by jimbo11883** [comment]
Same issue.

**Comment by jimbo11883** [comment]
Any updates on this issue?

**Comment by miguelbalparda** [comment]
It seems https://github.com/nexcess/magento-sentry-two-factor-authentication/pull/17 fixes this issue, can you give this a try and report back?

**Comment by jimbo11883** [comment]
It worked for me! Thanks!

**Comment by timothydmahon** [comment]
Ran into this issue after branching from master. Any word on when this will be merged into the master branch?
